name: TEST OKX LIST

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python kuruluyor
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Library install
        run: |
          pip install requests

      - name: OKX list test
        run: python okx_test_list.py
